const fs = require('fs');
const text = `
5th JUNE 2026 
1. YUSUF BABATUNDE 
2. OLUWAFEMI ISRAEL 
3. TIMOTHY AUSTINE 
4. AKOMOLAFE TOYINSOLA 
5. ADARAN KOLA CHARLES 
6. DADA GOODNEWS 
7. OLAWUYI SOLOMON 
8. EKUNDAYO SUCCESS 
9. TIWO OLUWASEYI 
10. AYANNA FERANMI 
11. AGU DESTINY 
12. ABOLARINWA FEMI 
13. EKUNDAYO LAUGHTER 
14. ADEBAYO STEPHEN 
15. OLANREWAJU EMMANUEL 
16. FATILE HEPZIBAH 
`;
fs.appendFileSync('./src/data/raw-devotion.txt', text);
